import {ReactNode} from 'react'
import {Analytics} from '@vercel/analytics/react'
import {Inter} from 'next/font/google'

import {Providers} from './provider'

import '../styles/globals.css'
import HeaderNaviBar from '@/components/navigation'

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='light' suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <HeaderNaviBar />

          <div className='relative flex min-h-screen flex-col'>
            <main className='flex-1'>{children}</main>
          </div>
        </Providers>
        <Analytics />
      </body>
    </html>
  )
}
