export const API_KEY = process.env.NEXT_PUBLIC_RIOT_GAMES_KEY
export const BASE_URL = process.env.NEXT_PUBLIC_RIOT_GAMES_BASE_URL
export const SUMMONER_NAME = process.env.NEXT_PUBLIC_RIOT_GAMES_SUMMONER_NAME
export const SUMMONER_LEAGUE = process.env.NEXT_PUBLIC_RIOT_GAMES_SUMMONER_LEAGUE
export const PROFILE_ICON = process.env.NEXT_PUBLIC_RIOT_GAMES_PROFILE_ICON

export const CHAMP_SPLASH_IMG = process.env.NEXT_PUBLIC_RIOT_GAMES_CHAMPION_SPLASH_IMG
export const CHAMP_SQUARE_IMG = process.env.NEXT_PUBLIC_RIOT_GAMES_CHAMPION_SQUARE_IMG
export const LEAGUE = process.env.NEXT_PUBLIC_RIOT_GAMES_LEAGUE
